<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <title>Generador de datos</title>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/style.css" />
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-md-offset-3">
				<h1 class="title-generator">
					Generador de datos
					<span class="small">v.Beta 8-)</span>
				</h1>
			</div>
		</div>
