<?php include('elements/header-template.phtml'); ?>

<div class="row">
	<?php

	if(isset($_GET["m"]))
	{
		switch($_GET["m"])
		{
			case '1';
			?>
				<div class="alert alert-danger" role="alert">
					 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					  <span class="sr-only">Error:</span>
					Ingrese la cantidad de registros a generar
				</div>
	        <?php
			break;

			case '2';
			?>
				<div class="alert alert-danger" role="alert">
					 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					  <span class="sr-only">Error:</span>
					Ingrese una cantidad numerica
				</div>
	        <?php
			break;

			case '3';
			?>
				<div class="alert alert-danger" role="alert">
					 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					  <span class="sr-only">Error:</span>
					Lo siento, tu solicitud no pudo ser procesada :-(
				</div>
	        <?php
			break;

			case '4';
			?>
				<div class="alert alert-success" role="alert">
					 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					  <span class="sr-only">Error:</span>
					La columna fue poblada con éxito 8-)
				</div>
	        <?php
			break;

			case '5';
			?>
				<div class="alert alert-danger" role="alert">
					 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					  <span class="sr-only">Error:</span>
					Debe seleccionar una de las poblaciones disponibles
				</div>
	        <?php
			break;

		}
	}

	?>
	<div class="col-md-6">
		<div class="page-header">
			<h3>Poblando el campo <?php echo $_GET['column'] ?></h3>
		</div>
		<form action="" method="POST" class="form">
			<div class="form-group">
				<label for="cantidad">Cantidad de datos a poblar: </label>
				<input type="text" name="quantityOfRowsFromTable" class="form-control" id="cantidad" >
			</div>
			<div class="form-group">
				<label for="option">Poblaciones disponibles: </label>
				<select name="<?php echo $_GET['column']; ?>" id="option" class="form-control">
					<option value="empty">Seleccione un campo...</option>
						<?php for($j = 0; $j < count($get_table_generator); $j++){ ?>
						<optgroup label="<?php echo $get_table_generator[$j][0]; ?>">
							<?php for($k = 0; $k < count($get_column_generator); $k++){ ?>
								<?php if($get_column_generator[$k]['table'] == $get_table_generator[$j][0]){ ?>
									<option value="<?php echo $get_column_generator[$k][0]['Field']; ?>"><?php echo $get_column_generator[$k][0]['Field']; ?></option>
								<?php } ?>
							<?php } ?>
						</optgroup>
					<?php } ?>
				</select>
			</div>
			<br><br>
			<input type="hidden" name="recordToVerify" value="si" />
			<input type="hidden" name="initial_table" value="<?php echo $_GET["table"]; ?>" />
			<input type="hidden" name="initial_column" value="<?php echo $_GET["column"]; ?>" />


			<a href="<?php echo Conectar::ruta();?>?accion=fill_table&table=<?php echo $_GET["table"];?>" class="btn btn-primary">
				<span class="glyphicon glyphicon-chevron-left"></span>
				Volver
			</a>
			<button class="btn btn-primary">
				Procesar
				<span class="glyphicon glyphicon-chevron-right"></span>
			</button>
			<a href="<?php echo Conectar::ruta();?>?accion=finish" class="btn btn-primary">
				Finalizar
				<span class="glyphicon glyphicon-log-out"></span>
			</a>

		</form>
	</div>
</div>

<?php include('elements/footer-template.phtml'); ?>