<?php include('elements/header-template.phtml'); ?>

<div class="row">
<?php

if(isset($_GET["m"]))
{
	switch($_GET["m"])
	{
		case '1';
		?>
			<div class="alert alert-danger" role="alert">
				 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				  <span class="sr-only">Error:</span>
				Ingrese una base de datos
			</div>
        <?php
		break;

		case '2';
		?>
			<div class="alert alert-danger" role="alert">
				 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				  <span class="sr-only">Error:</span>
				La base de datos no existe, por favor ingrese una base de datos valida.
			</div>
        <?php
		break;

		case '3';
		?>
			<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only">Error:</span>
				No se pudo acceder al contenido, intente nuevamente.
			</div>
        <?php
		break;
	}
}

?>

	<div class="col-md-6">
		<p class="lead">Ingresa la base de datos en la que trabajaremos: </p>
		<form action="<?php echo Conectar::ruta();?>?accion=check_database" method="POST" class="form">
			<fieldset>
				<div class="form-group">
					<label for="bd">Base de datos:</label>
					<input type="text" name="database" class="form-control" id="bd" />
				</div>

				<div class="form-group">
					<button class="btn btn-primary">
						Siguiente
						<span class="glyphicon glyphicon-chevron-right"></span>
					</button>
				</div>
				<!-- <input type="hidden" name="grabar" value="si" /> -->
			</fieldset>
		</form>
	</div>
</div>

<?php include('elements/footer-template.phtml'); ?>