          <ul class="sf-menu" id="nav">
            <li><a href="<?php echo Conectar::ruta(); ?>?accion=index">Inicio</a></li>
            <li><a href="<?php echo Conectar::ruta(); ?>?accion=logueo">Ingresar</a></li>
            <li><a href="#">A Page</a></li>
            <li><a href="#">Another Page</a></li>
            <li><a href="#">Example Drop Down</a>
              <ul>
                <li><a href="#">Drop Down One</a></li>
                <li><a href="#">Drop Down Two</a>
                  <ul>
                    <li><a href="#">Sub Drop Down One</a></li>
                    <li><a href="#">Sub Drop Down Two</a></li>
                    <li><a href="#">Sub Drop Down Three</a></li>
                    <li><a href="#">Sub Drop Down Four</a></li>
                    <li><a href="#">Sub Drop Down Five</a></li>
                  </ul>
                </li>
                <li><a href="#">Drop Down Three</a></li>
                <li><a href="#">Drop Down Four</a></li>
                <li><a href="#">Drop Down Five</a></li>
              </ul>
            </li>
            <li><a href="#">Contact Us</a></li>
          </ul>